var shuffleSequence = seq("intro", sepWith("sep",  seq("practice")), "practiceover", sepWith("sep", rshuffle(startsWith("first"), startsWith("filler"))));

var continueMessage = ["Klikni zde"];

var aj = "AcceptabilityJudgment";

var q = "Question";

var completionMessage = "[Zadané odpovědi jsou odeslány na server. Děkujeme za spolupráci!]";

var ms = "Message";

var defaults = [
    "Separator", { transfer: 800,
                   normalMessage: "Počkejte prosím na další položku v experimentu.",
                   errorMessage: "Špatně. Počkejte prosím na další položku v experimentu."
         },
    "AcceptabilityJudgment", { as: ["levý", "pravý", "ani jeden"],
                              presentAsScale: false,
                              leftComment: "(věta v kontextu odpovídá levému obrázku)",
                              rightComment: "(věta v kontextu odpovídá pravému obrázku)",
                               randomOrder: false,
                               showNumbers: false,
                               },
    "Message", { hideProgressBar: true, transfer: "click" }
];

var progressBarText = "";

var items = [ ["sep", "Separator", { }],

          ["intro", "Form", {continueMessage: "Pro vstup do experimentu, klikněte zde", html: { include: "example_intro.html" }}],

          ["practice", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpeg?raw=true\"></td></table></center>Kontext: Practice kontext 1<center><p>Věta: <i>Practice věta 1.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}, hasCorrect: 0}],
["practice", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpeg?raw=true\"></td></table></center>Kontext: Practice kontext 2.</p><center><p>Věta: <i>Practice věta 2.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}, hasCorrect: 1}],

          ["practiceover", "Message", {continueMessage: "Klikněte zde pro pokračování experimentu", html: ["div", ["p", "Zde končí přípravná část experimentu. Klikněte níže pro vstup do experimentu."]]}],

[["first-item1-d-ref", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM 1-D-REF] Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Karel i Jakub vyfotili dvě herečky. Karel i Jakub photographed two actors.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["first-item1-d-svo", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM 1-D-SVO]Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Dva novináři vyfotili Simonu i Kamilu. Two journalists photographed Simona i Kamila.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["first-item1-d-move-a", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM 1-D-MOVE-A]Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Na večírku byly Simona i Kamila vyfoceny dvěma novináři. At the party Simona i Kamila were photographed by two journalists.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["first-item1-d-move-abar", 1], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM 1-D-MOVE-ABAR]Kontext: Včera se konal v Praze večírek celebrit. Sešli se zde známí herci, zpěváci, modelky a samozřejmě novináři bulvárních časopisů. Večírku se zúčastnily také herečky Simona a Kamila. Šéfredaktoři přikázali novinářům pořídit fotografie ukazující temnou stránku celebrit. Novináři Karel a Jakub tedy doufali, že se jim pořadí pořídit kompromitující fotografie pozvaných osobností, které by mohly čtenáře časopisů zajímat.</p><center><p>Věta: <i> Simonu i Kamilu dva novináři vyfotili až po půlnoci. Simona i Kamila two journalists photographed after midnight.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
             

[["first-item2-nd-ref", 2], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-2-ND-REF]Kontext: Minulý víkend se konal na výstavišti kutilský veletrh, v rámci kterého byly pořádány soutěže. Úkolem jedné z nich bylo vyrobit dřevený výrobek za 6 hodin. Nejkrásnější výrobky byly hodnoceny porotou. Soutěžící mohli porotě předložit k hodnocení libovolný počet výrobků, ovšem výrobky, které nestihly dokončit během daného časového limitu, nebyly brány porotou v úvahu. Soutěže se mohly zúčastnit týmy i jednotlivci.</p><center><p>Věta: <i>Muž i žena vyrobili dva dřevěné výrobky. A man i a woman made two wooden objects.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["first-item2-nd-svo", 2], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-2-ND-SVO]Kontext: Minulý víkend se konal na výstavišti kutilský veletrh, v rámci kterého byly pořádány soutěže. Úkolem jedné z nich bylo vyrobit dřevený výrobek za 6 hodin. Nejkrásnější výrobky byly hodnoceny porotou. Soutěžící mohli porotě předložit k hodnocení libovolný počet výrobků, ovšem výrobky, které nestihly dokončit během daného časového limitu, nebyly brány porotou v úvahu. Soutěže se mohly zúčastnit týmy i jednotlivci.</p><center><p>Věta: <i>Dva soutěžící vyrobili židli i ptačí budku. Two competitors made a chair i a bird house.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["first-item2-nd-move-a", 2], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-2-ND-MOVE-A]Kontext: Minulý víkend se konal na výstavišti kutilský veletrh, v rámci kterého byly pořádány soutěže. Úkolem jedné z nich bylo vyrobit dřevený výrobek za 6 hodin. Nejkrásnější výrobky byly hodnoceny porotou. Soutěžící mohli porotě předložit k hodnocení libovolný počet výrobků, ovšem výrobky, které nestihly dokončit během daného časového limitu, nebyly brány porotou v úvahu. Soutěže se mohly zúčastnit týmy i jednotlivci.</p><center><p>Věta: <i>Na veletrhu byly židle i ptačí budka vyrobeny dvěma soutěžícími. At the Exhibition Center, a chair i a bird house were made by two competitors.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
             
[["first-item2-nd-move-abar", 2], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-2-ND-MOVE-A]Kontext: Minulý víkend se konal na výstavišti kutilský veletrh, v rámci kterého byly pořádány soutěže. Úkolem jedné z nich bylo vyrobit dřevený výrobek za 6 hodin. Nejkrásnější výrobky byly hodnoceny porotou. Soutěžící mohli porotě předložit k hodnocení libovolný počet výrobků, ovšem výrobky, které nestihly dokončit během daného časového limitu, nebyly brány porotou v úvahu. Soutěže se mohly zúčastnit týmy i jednotlivci.</p><center><p>Věta: <i>Židle i ptačí budku dva soutěžící vyrobili během daného limitu. A chair i a bird house two competitors made within the time limit.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["first-item3-nd-ref", 3], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-3-ND-REF]Kontext: Starosta města musel posílit policejní hlídky, protože se ve městě objevila skupina zlodějů, kteří rabovali obchody a okrádali občany. Zlodějům veleli Tomáš a Robin. Starosta doufal, že se policistům podaří vůdce zlodějů chytit předtím, než začne jarní festival. K případu byli přidělení policisté Jaroslav a Svatopluk.</p><center><p>Věta: <i>Jaroslav i Svatopluk uvěznili dva výtržníky. Jaroslav i Svatopluk arrested two thieves.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],

[["first-item3-nd-svo", 3], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-3-ND-SVO]Kontext: Starosta města musel posílit policejní hlídky, protože se ve městě objevila skupina zlodějů, kteří rabovali obchody a okrádali občany. Zlodějům veleli Tomáš a Robin. Starosta doufal, že se policistům podaří vůdce zlodějů chytit předtím, než začne jarní festival. K případu byli přidělení policisté Jaroslav a Svatopluk.</p><center><p>Věta: <i>Dva policisté uvěznili Robina i Tomáše. Two policemen arrested Robin i Thomas.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
             
[["first-item3-nd-move-a", 3], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-3-ND-MOVE-A]Kontext: Starosta města musel posílit policejní hlídky, protože se ve městě objevila skupina zlodějů, kteří rabovali obchody a okrádali občany. Zlodějům veleli Tomáš a Robin. Starosta doufal, že se policistům podaří vůdce zlodějů chytit předtím, než začne jarní festival. K případu byli přidělení policisté Jaroslav a Svatopluk.</p><center><p>Věta: <i>Ještě před zahájením jarního festivalu byli Robin i Tomáš uvězněni dvěma policisty. Before the beginning of the spring festival, Robin i Thomas were arrested by two policemen.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],             
            
[["first-item3-nd-move-abar", 3], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-3-ND-MOVE-ABAR]Kontext: Starosta města musel posílit policejní hlídky, protože se ve městě objevila skupina zlodějů, kteří rabovali obchody a okrádali občany. Zlodějům veleli Tomáš a Robin. Starosta doufal, že se policistům podaří vůdce zlodějů chytit předtím, než začne jarní festival. K případu byli přidělení policisté Jaroslav a Svatopluk.</p><center><p>Věta: <i>Robina i Tomáše dva policisté uvěznili ještě před zahájením jarního festivalu. Robin i Thomas two policemen arrested before the beginning of the spring festival.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}], 
  
[["first-item4-d-ref", 4], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-4-D-REF]Kontext: Karel a Petr pracují oba ve firmě, která provádí malířské a natěračské práce. Minulý pátek pracovali v naší ulici. Dva domy nutně potřebovaly nově natřít: vila a rodinný dům.</p><center><p>Věta: <i>Karel i Petr natřeli dva domy nažluto. Karel i Petr painted two houses yellow.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              

[["first-item4-d-svo", 4], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-4-D-SVO]Kontext: Karel a Petr pracují oba ve firmě, která provádí malířské a natěračské práce. Minulý pátek pracovali v naší ulici. Dva domy nutně potřebovaly nově natřít: vila a rodinný dům.</p><center><p>Věta: <i>Dva natěrači natřeli rodinný dům i vilu nažluto. Two painters painted a family house i a villa yellow.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
[["first-item4-d-move-a", 4], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-4-D-MOVE-A]Kontext: Karel a Petr pracují oba ve firmě, která provádí malířské a natěračské práce. Minulý pátek pracovali v naší ulici. Dva domy nutně potřebovaly nově natřít: vila a rodinný dům.</p><center><p>Věta: <i>V naší ulici byly rodinný dům i vila natřeny nažluto dvěma natěrači. In my street, a family house i a villa were painted yellow by two painters.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],               
  
[["first-item4-d-move-abar", 4], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-4-D-MOVE-ABAR]Kontext: Karel a Petr pracují oba ve firmě, která provádí malířské a natěračské práce. Minulý pátek pracovali v naší ulici. Dva domy nutně potřebovaly nově natřít: vila a rodinný dům.</p><center><p>Věta: <i>Rodinný dům i vilu dva natěrači natřeli nažluto. A family house i a villa two painters painted yellow.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
[["first-item5-nd-ref", 5], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_non-distribtive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-5-ND-REF]Kontext: V naší vesnici se rozmohlo rušení nočního klidu z důvodu otevření nové herny. Zastupitelé vesnice situaci projednali a rozhodli o nových vyhláškách: jedna říká, že rušení nočního klidu je nezákonné, a druhá upravuje zákon o hazardních hrách. Vyhlášky vyvěsili šéf policie a starosta.</p><center><p>Věta: <i>Starosta i šéf policie pověsili na vývěsní desku dvě vyhlášky. The major i the Chief of Police put two public notices on the notice board.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
[["first-item5-nd-svo", 5], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_non-distribtive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-5-ND-SVO]Kontext: V naší vesnici se rozmohlo rušení nočního klidu z důvodu otevření nové herny. Zastupitelé vesnice situaci projednali a rozhodli o nových vyhláškách: jedna říká, že rušení nočního klidu je nezákonné, a druhá upravuje zákon o hazardních hrách. Vyhlášky vyvěsili šéf policie a starosta.</p><center><p>Věta: <i>Dva úředníci pověsili vyhlášku o nočním klidu i vyhlášku o provozování hazardu na vývěsní desku. Two officials put a public notice concerning to the peace at night i a public notice concerning to gambling regulation on the notice board.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
[["first-item5-nd-move-a", 5], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_non-distribtive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-5-ND-MOVE-A]Kontext: V naší vesnici se rozmohlo rušení nočního klidu z důvodu otevření nové herny. Zastupitelé vesnice situaci projednali a rozhodli o nových vyhláškách: jedna říká, že rušení nočního klidu je nezákonné, a druhá upravuje zákon o hazardních hrách. Vyhlášky vyvěsili šéf policie a starosta.</p><center><p>Věta: <i>Na vývěsní desku byly pověšeny vyhláška o nočním klidu i vyhláška o provozování hazardu schváleny dvěma úředníky. On the notice board, a public notice concerning to the peace at night i a public notice concerning to gambling regulation were put by two officials.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],       
             
[["first-item5-nd-move-abar", 5], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_non-distribtive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_nd_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-5-ND-MOVE-ABAR]Kontext: V naší vesnici se rozmohlo rušení nočního klidu z důvodu otevření nové herny. Zastupitelé vesnice situaci projednali a rozhodli o nových vyhláškách: jedna říká, že rušení nočního klidu je nezákonné, a druhá upravuje zákon o hazardních hrách. Vyhlášky vyvěsili šéf policie a starosta.</p><center><p>Věta: <i>Vyhlášku o nočním klidu i vyhlášku o provozování hazardu dva úřednící pověsili na úřední desku. A public notice concerning to the peace at night i a public notice concerning to gambling regulation two officials put on the notice board.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],           
             
[["first-item6-d-ref", 6], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-6-D-REF]Kontext: V centru města se stala dopravní nehoda. Naštěstí nebyl nikdo vážně zraněn. Někteří lidé byli přesto převezeni do nemocnice, kde byli ošetřeni zdravotníky.</p><center><p>Věta: <i>Doktor i doktorka ošetřili dva zraněné pacienty. A doctor (male) i a doctor (female) treated two injured patiens.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
[["first-item6-d-svo", 6], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-6-D-SVO]Kontext: V centru města se stala dopravní nehoda. Naštěstí nebyl nikdo vážně zraněn. Někteří lidé byli přesto převezeni do nemocnice, kde byli ošetřeni zdravotníky.</p><center><p>Věta: <i>Dva doktoři ošetřili staršího muže i dítě. Two doctors treated an elderly man i a child.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],       
             
[["first-item6-d-move-a", 6], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-6-D-MOVE-A]Kontext: V centru města se stala dopravní nehoda. Naštěstí nebyl nikdo vážně zraněn. Někteří lidé byli přesto převezeni do nemocnice, kde byli ošetřeni zdravotníky.</p><center><p>Věta: <i>V nemocnici byli starší muž i dítě ošetřeni dvěma doktory. In hospital, an elderly man i a child were treated by two doctors.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
[["first-item6-d-move-abar", 6], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-6-D-MOVE-ABAR]Kontext: V centru města se stala dopravní nehoda. Naštěstí nebyl nikdo vážně zraněn. Někteří lidé byli přesto převezeni do nemocnice, kde byli ošetřeni zdravotníky.</p><center><p>Věta: <i>Staršího muže i dítě dva doktoři ošetřili v nemocnici. An elderly man i a child two doctors treated in hospital.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],       
             
[["first-item7-nd-ref", 7], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_nd_wrong%20new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-7-ND-REF]Kontext: V kině tento týden začali dávat nový film o válce mezi roboty a lidmi. Roboti mají různé barvy podle jejich vojenské hodnosti. Roboti se chovají brutálně a nerozlišují mezi vojáky a civilisty. Hlavní hrdina, který patří k vojenské jednotce, přežije, ale někteří jeho kamarádi zemřou.</p><center><p>Věta: <i>Zelený robot i fialový robot zabili dva lidi. The green robot i the purple robot killed two people.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],               

[["first-item7-nd-svo", 7], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_nd_wrong%20new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-7-ND-SVO]Kontext: V kině tento týden začali dávat nový film o válce mezi roboty a lidmi. Roboti mají různé barvy podle jejich vojenské hodnosti. Roboti se chovají brutálně a nerozlišují mezi vojáky a civilisty. Hlavní hrdina, který patří k vojenské jednotce, přežije, ale někteří jeho kamarádi zemřou.</p><center><p>Věta: <i>Dva roboti zabili vojáka i civilistu. Two robots killed a soldier i a civilian.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],           
             
[["first-item7-nd-move-a", 7], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_nd_wrong%20new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-7-ND-MOVE-A]Kontext: V kině tento týden začali dávat nový film o válce mezi roboty a lidmi. Roboti mají různé barvy podle jejich vojenské hodnosti. Roboti se chovají brutálně a nerozlišují mezi vojáky a civilisty. Hlavní hrdina, který patří k vojenské jednotce, přežije, ale někteří jeho kamarádi zemřou.</p><center><p>Věta: <i>V džungli byli voják i civilista zabiti dvěma roboty. In the jungle, a soldier i a civilian were killed by two robots.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],               
             
[["first-item7-nd-move-abar", 7], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_non-distributive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_nd_wrong%20new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-7-ND-MOVE-ABAR]Kontext: V kině tento týden začali dávat nový film o válce mezi roboty a lidmi. Roboti mají různé barvy podle jejich vojenské hodnosti. Roboti se chovají brutálně a nerozlišují mezi vojáky a civilisty. Hlavní hrdina, který patří k vojenské jednotce, přežije, ale někteří jeho kamarádi zemřou.</p><center><p>Věta: <i>Vojáka i civilistu dva roboti zabili v džungli. A soldier i a civilian two robots killed on a military base.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],       
             
[["first-item8-d-ref", 8], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-8-D-REF]Kontext: Skupina zlodějů se vloupala do obchodu, kde chtěli ukrást peníze a drahou elektroniku. Jejich počínání přerušil příchod zaměstnanců obchodu, kteří okamžitě zavolali policii. Při pokusu utéct zloději zaměstnance fyzicky napadli. Policie naštěstí zasáhla včas, ale někteří zaměstnanci museli být ošetřeni lékařem.</p><center><p>Věta: <i>Zloděj i zlodějka zranili dva zaměstnance. A robber (man) i a robber (woman) injured two employees.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],    
             
[["first-item8-d-svo", 8], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-8-D-SVO]Kontext: Skupina zlodějů se vloupala do obchodu, kde chtěli ukrást peníze a drahou elektroniku. Jejich počínání přerušil příchod zaměstnanců obchodu, kteří okamžitě zavolali policii. Při pokusu utéct zloději zaměstnance fyzicky napadli. Policie naštěstí zasáhla včas, ale někteří zaměstnanci museli být ošetřeni lékařem.</p><center><p>Věta: <i>Dva zloději zranili prodavače i prodavačku. Two robbers injured a shop assistant (man) i a shop assistant (woman).</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],               
[["first-item8-d-move-a", 8], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-8-D-MOVE-A]Kontext: Skupina zlodějů se vloupala do obchodu, kde chtěli ukrást peníze a drahou elektroniku. Jejich počínání přerušil příchod zaměstnanců obchodu, kteří okamžitě zavolali policii. Při pokusu utéct zloději zaměstnance fyzicky napadli. Policie naštěstí zasáhla včas, ale někteří zaměstnanci museli být ošetřeni lékařem.</p><center><p>Věta: <i>V obchodě byli prodavač i prodavačka zraněni dvěma zloději. In the shop, a shop assistant (man) i a shop assistant (woman) were injured by two robbers.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],     
             
[["first-item8-d-move-abar", 8], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_distributive_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_d_wrong_new.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-8-D-MOVE-ABAR]Kontext: Skupina zlodějů se vloupala do obchodu, kde chtěli ukrást peníze a drahou elektroniku. Jejich počínání přerušil příchod zaměstnanců obchodu, kteří okamžitě zavolali policii. Při pokusu utéct zloději zaměstnance fyzicky napadli. Policie naštěstí zasáhla včas, ale někteří zaměstnanci museli být ošetřeni lékařem.</p><center><p>Věta: <i>Prodavače i prodavačku dva zloději zranili v obchodě. A shop assistant (man) i a shop assistant (woman) two robbers injured in the shop.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
[["first-item9-d-ref", 9], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-9-D-REF]Kontext: Chlapeček a holčička byli moc rozmazlení a nevážili si věcí, které dostali od rodičů. Odpoledne si spolu děti hrály a poškodily několik hraček.</p><center><p>Věta: <i>Chlapeček i holčička poškodili dvě hračky. The little boy i the little girl damaged two toys.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
[["first-item9-d-svo", 9], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-9-D-SVO]Kontext: Chlapeček a holčička byli moc rozmazlení a nevážili si věcí, které dostali od rodičů. Odpoledne si spolu děti hrály a poškodily několik hraček.</p><center><p>Věta: <i>Dvě děti poškodily autíčko i panenku. Two children damaged a toy car i a doll.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
[["first-item9-d-move-a", 9], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-9-D-MOVE-A]Kontext: Chlapeček a holčička byli moc rozmazlení a nevážili si věcí, které dostali od rodičů. Odpoledne si spolu děti hrály a poškodily několik hraček.</p><center><p>Věta: <i>Odpoledne byly autíčko i panenka poškozeny dvěma dětmi. In the afternoon, a toy car i a doll were damaged by two children.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
[["first-item9-d-move-abar", 9], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-9-D-MOVE-ABAR]Kontext: Chlapeček a holčička byli moc rozmazlení a nevážili si věcí, které dostali od rodičů. Odpoledne si spolu děti hrály a poškodily několik hraček.</p><center><p>Věta: <i>Autíčko i panenku dvě děti poškodily odpoledne. A toy car i a doll two children damaged in the afternoon.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],         
             
[["first-item10-nd-ref", 10], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-10-ND-REF]Kontext: Na dětském pirátském táboře byly děti rozděleny do skupin. Každá skupina dostala za úkol zvolit si název své pirátské lodi a vyrobit vlastní vlajku. Po celé dva týdny děti sbíraly body za plnění různých úkolů. Každý večer byly před večeří pověšeny před hlavním stanem vlajky a byl vyhlášen počet získaných bodů jednotlivých skupin.</p><center><p>Věta: <i>Kluk i dívka pověsili dvě vlajky dnes večer. A boy i a girl hanged two flags this evening.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],             
 
[["first-item10-nd-svo", 10], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-10-ND-SVO]Kontext: Na dětském pirátském táboře byly děti rozděleny do skupin. Každá skupina dostala za úkol zvolit si název své pirátské lodi a vyrobit vlastní vlajku. Po celé dva týdny děti sbíraly body za plnění různých úkolů. Každý večer byly před večeří pověšeny před hlavním stanem vlajky a byl vyhlášen počet získaných bodů jednotlivých skupin.</p><center><p>Věta: <i>Dnes večer dvě děti pověsily zelenou vlajku i červenou vlajku. This evening two children hanged a green flag i a red flag.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
[["first-item10-nd-move-a", 10], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-10-ND-MOVE-A]Kontext: Na dětském pirátském táboře byly děti rozděleny do skupin. Každá skupina dostala za úkol zvolit si název své pirátské lodi a vyrobit vlastní vlajku. Po celé dva týdny děti sbíraly body za plnění různých úkolů. Každý večer byly před večeří pověšeny před hlavním stanem vlajky a byl vyhlášen počet získaných bodů jednotlivých skupin.</p><center><p>Věta: <i>Dnes večer byly zelená vlajka i červená vlajka pověšeny dvěma dětmi. This evening a green flag i a red flag were hanged by two children.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
[["first-item10-nd-move-abar", 10], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-10-ND-MOVE-ABAR]Kontext: Na dětském pirátském táboře byly děti rozděleny do skupin. Každá skupina dostala za úkol zvolit si název své pirátské lodi a vyrobit vlastní vlajku. Po celé dva týdny děti sbíraly body za plnění různých úkolů. Každý večer byly před večeří pověšeny před hlavním stanem vlajky a byl vyhlášen počet získaných bodů jednotlivých skupin.</p><center><p>Věta: <i>Zelenou vlajku i červenou vlajku dvě děti pověsily dnes večer. A green flag i a red flag two children hanged this evening.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],    
             
[["first-item11-nd-ref", 11], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-11-ND-REF]Kontext: Slavný spisovatel napsal román Svět a básnickou sbírku Jupiter. Oslovil dvě brněnská nakladatelství Host a Jota, která nakonec souhlasila, že mu knihy vydají.</p><center><p>Věta: <i>Host i Jota vydaly dvě knihy. Host i Jota published two books.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
 
[["first-item11-nd-svo", 11], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-11-ND-SVO]Kontext: Slavný spisovatel napsal román Svět a básnickou sbírku Jupiter. Oslovil dvě brněnská nakladatelství Host a Jota, která nakonec souhlasila, že mu knihy vydají.</p><center><p>Věta: <i>Dvě nakladatelství vydala román i básnickou sbírku. Two publishing houses published a novel i a poetry collection.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],            
             
[["first-item11-nd-move-a", 11], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-11-ND-MOVE-A]Kontext: Slavný spisovatel napsal román Svět a básnickou sbírku Jupiter. Oslovil dvě brněnská nakladatelství Host a Jota, která nakonec souhlasila, že mu knihy vydají.</p><center><p>Věta: <i>Román i básnická sbírka byly vydány dvěma nakladatelstvími. A novel i a poetry collection were published by two publishing houses.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],               
[["first-item11-nd-move-abar", 11], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-11-ND-MOVE-ABAR]Kontext: Slavný spisovatel napsal román Svět a básnickou sbírku Jupiter. Oslovil dvě brněnská nakladatelství Host a Jota, která nakonec souhlasila, že mu knihy vydají.</p><center><p>Věta: <i>Román i básnickou sbírku dvě nakladatelství vydala v Brně. A novel i a poetry collection two publishing houses published in Brno.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],            
[["first-item12-d-ref", 12], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_d_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-12-D-REF]Kontext: Na středověký jarmark se sjeli příznivci z celého okolí. Prodavači byli oblečeni do typických středověkých kostýmů a prodávali ručně vyrobené výrobky. Mezi oblíbené patřily stánky kovářů, kteří na přání zákazníků ukovali ozdobné železné předměty.</p><center><p>Věta: <i>Kovář i kovářka ukovali dva železné předměty. A blacksmith (man) i a blacksmith (woman) forged two iron items.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
[["first-item12-d-svo", 12], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_d_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-12-D-SVO]Kontext: Na středověký jarmark se sjeli příznivci z celého okolí. Prodavači byli oblečeni do typických středověkých kostýmů a prodávali ručně vyrobené výrobky. Mezi oblíbené patřily stánky kovářů, kteří na přání zákazníků ukovali ozdobné železné předměty.</p><center><p>Věta: <i>Dva kováři ukovali želežnou podkovu i železný meč. Two blacksmiths forged an iron horseshoe i an iron sword.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
[["first-item12-d-move-a", 12], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_d_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-12-D-MOVE-A]Kontext: Na středověký jarmark se sjeli příznivci z celého okolí. Prodavači byli oblečeni do typických středověkých kostýmů a prodávali ručně vyrobené výrobky. Mezi oblíbené patřily stánky kovářů, kteří na přání zákazníků ukovali ozdobné železné předměty.</p><center><p>Věta: <i>Na jarmarku byly železná podkova i železný meč ukovány dvěma kováři. At the fair, an iron horseshoe i an iron sword were forged by two blacksmiths.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
[["first-item12-d-move-abar", 12], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_d_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-12-D-MOVE-ABAR]Kontext: Na středověký jarmark se sjeli příznivci z celého okolí. Prodavači byli oblečeni do typických středověkých kostýmů a prodávali ručně vyrobené výrobky. Mezi oblíbené patřily stánky kovářů, kteří na přání zákazníků ukovali ozdobné železné předměty.</p><center><p>Věta: <i> Železnou podkovu i železý meč dva kováři ukovali na jarmarku. An iron horseshoe i an iron rose two blacksmiths forged at the fair.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
[["first-item13-d-ref", 13], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-13-D-REF]Kontext: Holčička Lenka si na narozeniny přála dvě ručně ušitá třička různé barvy. Jedno tričko mělo být žluté a druhé růžové. Maminka a babička se rozhodly, že holčičce udělají radost, nakoupily látku a po nocích tajně šily.</p><center><p>Věta: <i>Maminka i babička ušily Lence k narozeninám dvě trička. Mom i grandmother sewed two shirts for Lenka’s birthday.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
[["first-item13-d-svo", 13], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-13-D-SVO]Kontext: Holčička Lenka si na narozeniny přála dvě ručně ušitá třička různé barvy. Jedno tričko mělo být žluté a druhé růžové. Maminka a babička se rozhodly, že holčičce udělají radost, nakoupily látku a po nocích tajně šily.</p><center><p>Věta: <i>Dvě ženy ušily růžové tričko i žluté tričko Lence k narozeninám. Two women sewed a pink shirt i a yellow shirt for Lenka’s birthday.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],            
             
[["first-item13-d-move-a", 13], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-13-D-MOVE-A]Kontext: Holčička Lenka si na narozeniny přála dvě ručně ušitá třička různé barvy. Jedno tričko mělo být žluté a druhé růžové. Maminka a babička se rozhodly, že holčičce udělají radost, nakoupily látku a po nocích tajně šily.</p><center><p>Věta: <i>K Lenčiným narozeninám byly růžové tričko i žluté tričko ušity dvěma ženami. For Lenka’s birthday, a pink shirt i a yellow shirt were sewed by two women.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],    
             
[["first-item13-d-move-abar", 13], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-13-D-MOVE-ABAR]Kontext: Holčička Lenka si na narozeniny přála dvě ručně ušitá třička různé barvy. Jedno tričko mělo být žluté a druhé růžové. Maminka a babička se rozhodly, že holčičce udělají radost, nakoupily látku a po nocích tajně šily.</p><center><p>Věta: <i>Růžové tričko i žluté tričko dvě ženy ušily Lence k narozeninám. A pink shirt i a yellow shirt two women sewed for Lenka’s birthday.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
[["first-item14-nd-ref", 14], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-14-ND-REF]Kontext: V jedné pohádce šel chalupník a statkář na trh koupit krávy. Cestou potkali mluvícího koně a mluvící prase, kteří jim řekli, že když je nakopnou, dají každému z nich zlatou minci.</p><center><p>Věta: <i>Chalupník i statkář nakopli dvě zvířata. A cottager i a landowner kicked two animals.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
[["first-item14-nd-svo", 14], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-14-ND-SVO]Kontext: V jedné pohádce šel chalupník a statkář na trh koupit krávy. Cestou potkali mluvícího koně a mluvící prase, kteří jim řekli, že když je nakopnou, dají každému z nich zlatou minci.</p><center><p>Věta: <i>Dva vesničané nakopli koně i prase. Two villagers kicked a horse i a donkey.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
[["first-item14-nd-move-a", 14], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-14-ND-MOVE-A]Kontext: V jedné pohádce šel chalupník a statkář na trh koupit krávy. Cestou potkali mluvícího koně a mluvící prase, kteří jim řekli, že když je nakopnou, dají každému z nich zlatou minci.</p><center><p>Věta: <i>Na cestě byly kůň i prase nakopnuty dvěma vesničany. On the way, a horse i a donkey were kicked by two villagers.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
[["first-item14-nd-move-abar", 14], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd.jpg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd_f.jpg?raw=true\"></td></table></center>[DEBUG: ITEM-14-ND-MOVE-ABAR]Kontext: V jedné pohádce šel chalupník a statkář na trh koupit krávy. Cestou potkali mluvícího koně a mluvící prase, kteří jim řekli, že když je nakopnou, dají každému z nich zlatou minci.</p><center><p>Věta: <i>Koně i prase dva vesničané nakopli po cestě na trh. A horse i a cow two villagers kicked on the way to the market.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
             
[["first-item15-d-ref", 15], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_distributive.JPG?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_d_wrong.JPG?raw=true\"></td></table></center>[DEBUG: ITEM-15-D-REF]Kontext: Skupina kluků a dívek si odpoledne hrála před školní jídelnou s míči. Kluci si kopali se zeleným míčem a dívky si házely s červeným míčem. Druhý den ředitel školy zjistil, že děti rozbily míčem okna. Zavolal si je do ředitelny, aby odhalil viníka.</p><center><p>Věta: <i>Kluk i dívka rozbili dvě okna. A boy i a girl broke two windows.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
[["first-item15-d-svo", 15], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_distributive.JPG?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_d_wrong.JPG?raw=true\"></td></table></center>[DEBUG: ITEM-15-D-SVO]Kontext: Skupina kluků a dívek si odpoledne hrála před školní jídelnou s míči. Kluci si kopali se zeleným míčem a dívky si házely s červeným míčem. Druhý den ředitel školy zjistil, že děti rozbily míčem okna. Zavolal si je do ředitelny, aby odhalil viníka.</p><center><p>Věta: <i>Dvě děti rozbily čtvercové okno i kulaté okno. Two children broke square window i round window.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],     
             
[["first-item15-d-move-a", 15], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_distributive.JPG?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_d_wrong.JPG?raw=true\"></td></table></center>[DEBUG: ITEM-15-D-MOVE-A]Kontext: Skupina kluků a dívek si odpoledne hrála před školní jídelnou s míči. Kluci si kopali se zeleným míčem a dívky si házely s červeným míčem. Druhý den ředitel školy zjistil, že děti rozbily míčem okna. Zavolal si je do ředitelny, aby odhalil viníka.</p><center><p>Věta: <i>Ve školní jídelně byly čtvercové okno i kulaté okno rozbity dvěma dětmi. In the school canteen, square window i round window were broken by two children.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
[["first-item15-d-move-abar", 15], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_distributive.JPG?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_d_wrong.JPG?raw=true\"></td></table></center>[DEBUG: ITEM-15-D-MOVE-ABAR]Kontext: Skupina kluků a dívek si odpoledne hrála před školní jídelnou s míči. Kluci si kopali se zeleným míčem a dívky si házely s červeným míčem. Druhý den ředitel školy zjistil, že děti rozbily míčem okna. Zavolal si je do ředitelny, aby odhalil viníka.</p><center><p>Věta: <i>Čtvercové okno i kulaté okno dvě děti rozbily při hře s míčem. Square window i round window two children broke when playing with a ball.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],          
             
[["first-item16-nd-ref", 16], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-16-ND-REF]Kontext: O víkendu se syn a otec vydali na zahradu za domem, aby pokáceli staré stromy a místo nich vysadili nové. Obzvláště jeden dub a jeden smrk byly velmi staré a měly být pokáceny.</p><center><p>Věta: <i>Syn i otec pokáceli dva stromy. The son i the father cut down two trees.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
[["first-item16-nd-svo", 16], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-16-ND-SVO]Kontext: O víkendu se syn a otec vydali na zahradu za domem, aby pokáceli staré stromy a místo nich vysadili nové. Obzvláště jeden dub a jeden smrk byly velmi staré a měly být pokáceny.</p><center><p>Věta: <i>Dva muži pokáceli dub i smrk. Two men cut down an oak tree i a spruce tree.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],             
             
[["first-item16-nd-move-a", 16], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-16-ND-MOVE-A]Kontext: O víkendu se syn a otec vydali na zahradu za domem, aby pokáceli staré stromy a místo nich vysadili nové. Obzvláště jeden dub a jeden smrk byly velmi staré a měly být pokáceny.</p><center><p>Věta: <i>Na zahradě za domem byly dub i smrk pokáceny dvěma muži. In the garden behind the house, a oak tree i a spruce tree were cut down by two men.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],     
             
[["first-item16-nd-move-abar", 16], aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:290px;max-height:290px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:270px;max-height:270px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: ITEM-16-ND-MOVE-ABAR]Kontext: O víkendu se syn a otec vydali na zahradu za domem, aby pokáceli staré stromy a místo nich vysadili nové. Obzvláště jeden dub a jeden smrk byly velmi staré a měly být pokáceny.</p><center><p>Věta: <i>Dub i smrk dva muži pokáceli na zahradě. A oak tree i a spruce tree two men cut down in the garden.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
             
["filler1-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_nd_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/1_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: FILLER1-BAD]Kontext: Známý modní dům pořádal módní přehlídku nové kolekce. Bylo pozváno spoustu důležitých osob a také zástupci módních časopisů. Akci uzavírala noční přehlídka dvou světových modelek. Fotografové měli plné ruce práce.</p><center><p>Věta: <i>Každý fotograf vyfotil obě modelky. Each photographer photographed both models.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],
           
["filler2-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_d.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/3_non-d_f.jpg?raw=true\"></td></table></center>[DEBUG: FILLER3-GOOD]Kontext: Policisté pronásledovali skupinu zlodějů aut. Ti byli po krátké honičce s policisty dopadeni v kradených autech. Některým policistům se podařilo dopadnout a zatknout více zlodějů, někteří zůstali s policejními psy a nezatkli žádného zločince.</p><center><p>Věta: <i>Pouze jeden policista zatkl jednoho zloděje. Only one policeman arrested one thief.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}], 
             
["filler3-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_nd_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/2_non-distributive.jpg?raw=true\"></td></table></center>[DEBUG: FILLER2-BAD]Kontext: Na kutilském veletrhu si mohli účastníci vyzkoušet vyrobit předměty ze dřeva nebo železa pomocí starých středověkých postupů.</p><center><p>Věta: <i>Dva soutěžící vyrobili každý dva dřevěné výrobky.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],             
                         
["filler4-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_distribtive.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/5_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: FILLER5-GOOD]Kontext: Na policejním oddělení schválili dvě nové vyhlášky týkající se omezení rychlosti v některých částech města. Vyvěsit vyhlášku na úřední desku má v pravomoci úředník nebo policista.</p><center><p>Věta: <i>Pouze jedna osoba vyvěsila dvě vyhlášky na úřední desku. Only one person put two public notices on the notice board.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],   
             
["filler5-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_d_wrong_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/4_non-distributive_new.jpg?raw=true\"></td></table></center>[DEBUG: FILLER4-BAD]Kontext: Starosta města uspořádal soutěž malířů. Prvním úkolem bylo natřít dva domy v určitém limitu. Ti, kteří to zvládli, pokračovali do dalšího kola.</p><center><p>Věta: <i>Každý malíř zvládl natřít oba domy v daném limitu.Each painter managed to paint both houses within a given limit.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],    
             
["filler6-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_d_wrong_new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/8_distributive_new.jpg?raw=true\"></td></table></center>[DEBUG: FILLER8-GOOD]Kontext: Večerní televizní zprávy informovaly občany o dvou zlodějích, kteří vykrádají obchody. Většinou se snaží získat pouze peníze nebo věci, které by mohli později prodat. Někdy se bohužel uchylují i k násilí.</p><center><p>Věta: <i>Pouze jeden zloděj bodl prodavače. Only one thief stabbed a shop assistent.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
["filler7-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_nd_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/6_d_wrong.jpg?raw=true\"></td></table></center>[DEBUG: FILLER6-BAD]Kontext: Nový díl televizního seriálu <i>Naše město<i> se odehrával především v nemocnici, kde lékař Marek s lékařkou Annou ošetřovali zraněného dědečka s vnukem po autonehodě. Samozřejmě nechyběla romantická scéna mezi Markem a Annou.</p><center><p>Věta: <i>Dva lékaři ošetřili každý dva pacienty. Two doctors treated two patients each.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}], 
             
["filler8-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_d_f.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/9_nd.jpg?raw=true\"></td></table></center>[DEBUG: FILLER9-GOOD]Kontext: Dědeček měl radost, že se děti na oslavě jeho narozenin chovají vzorně a v klidu si hrají. Pak ale přišla jeho dcera se svými dětmi, kteří jsou pěkní rošťáci a rády ničí hračky. Díky přísnému tatínkovi se téměř nic nestalo.</p><center><p>Věta: <i>Pouze jedno dítě zničilo jednu hračku. Only one child damaged the toy.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],                        
["filler9-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_nd_wrong%20new.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/7_non-distributive.jpg?raw=true\"></td></table></center>[DEBUG: FILLER7-BAD]Kontext: Velmi oblíbenou počítačovou hrou se stali <i>Zabijáčtí roboti<i>. Tuto hru je možné hrát i s kamarády. Hráč si vybere jednoho robota. Úkolem je zabít určitý počet vojáků, a poté se hráč dostane na vyšší level hry.</p><center><p>Věta: <i>V prvním levelu hry každý robot zabil dva vojáky. Each robot killed two soldiers in the first level of the game.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],             
             
["filler10-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/10_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: FILLER10-GOOD]Kontext: Na dětském dnu měly děti za úkol vyrobit vlajku a s pomocí rodičů ji pověsit. Za odměnu pak získaly sladkosti.</p><center><p>Věta: <i>Každé dítě vyrobilo jednu vlajku. Each childern made one flag.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],  
             
["filler11-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/11_d_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: FILLER11-BAD]Kontext: Kniha <i>Jupiter<i> je po několik desetiletí oblíbenou dětskou knihou. Vyšla v několika edicích, ovšem pouze u jednoho nakladatelství.</p><center><p>Věta: <i>Pouze nakladatelství <i>Host<i> vydalo knihu <i>Jupiter<i>. Only the publishing house Host published the book Jupiter.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],    
             
["filler12-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_non-distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/12_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: FILLER12-GOOD]Kontext: Ve středověku se lidé scházeli na trzích, kde kupovali nebo prodávali různé předměty. Někteří prodávající předměty vyráběli přímo na místě.</p><center><p>Věta: <i>Dva vesničané vyrobili dva předměty ze železa. Two villagers made two iron objects.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
["filler13-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_d_wrong.jpg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/13_nd_wrong.jpeg?raw=true\"></td></table></center>[DEBUG: FILLER13-BAD]Kontext: Děti si při hře v lese roztrhly oblečení. Maminky z toho nebyly šťastné, ale rozhodly se, že dětem oblečení zašijí.</p><center><p>Věta: <i>Dvě maminky zašily dvě trička. Two moms sewed up two T-shirts.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],     
             
["filler14-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_d_f.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/14_nd.jpg?raw=true\"></td></table></center>[DEBUG: FILLER14-GOOD]Kontext: Farmář má velmi rád svá zvířata a dobře se o ně stará. Někdy ovšem, když má špatný den, nakopne slepice, které se mu pořád pletou pod nohy.</p><center><p>Věta: <i>Dnes farmář nakopl jednu slepici. The farmer kicked one hen today.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
["filler15-bad", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_distributive.JPG?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/15_non-distributive.jpeg?raw=true\"></td></table></center>[DEBUG: FILLER15-BAD]Kontext: Děti dostaly nové míčky různých barev. Odpoledne si s nimi házely o zeď. Tatínek se obával, že děti rozbijí míčkem okno, což se také stalo.</p><center><p>Věta: <i>Pouze červený míček rozbil okno. Only a red ball broke the window.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],      
             
["filler16-good", aj, {s: {html: "<center><table><table cellspacing=100><tr><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_distributive.jpeg?raw=true\"></td><td><img style=\"display:block;max-width:300px;max-height:300px;width: auto;height: auto;\" src=\"https://github.com/MojmirDocekal/jan_2019_brn_vie/blob/master/16_non-distributive.jpeg?raw=true\"></td></table></center>[DEBUG: FILLER16-GOOD]Kontext: Část lesa byl napaden kůrovcem, a proto se lesníci rozhodli, že stromy pokácí a vysadí nové.</p><center><p>Věta: <i>Dva lesníci pokáceli každý dva stromy. Two foresters cut down two trees each.</i></p></p>Větě v daném kontextu odpovídá obrázek:</center>"}}],              
             
];
